package com.platinumrelations.interview.payment_reconciliation.core.exception;

import lombok.Data;

import java.time.Instant;

/**
 * Uniform error payload returned by every REST endpoint on failure.
 *
 * <p>Messages are written for the API consumer and deliberately omit exception types, stack
 * frames, and row-level detail; the full cause is logged server-side by
 * {@link GlobalRestControllerExceptionHandler} instead, so diagnosing a failure never depends on
 * leaking internals to the caller.
 *
 * <p>Getters, setters, {@code equals}, {@code hashCode}, and {@code toString} are generated by
 * Lombok's {@code @Data}. The class is mutable and is intended to be created, serialised, and
 * discarded on a single request thread.
 *
 * @author John
 */
@Data
public class ErrorResponse {

    /**
     * Creates an error payload.
     *
     * @param message   the caller-facing description of what went wrong
     * @param timestamp when the failure was observed
     */
    public ErrorResponse(String message, Instant timestamp){
        this.message = message;
        this.timestamp = timestamp;
    }

    /** Caller-facing description of the failure; contains no internal or row-level detail. */
    private String message;
    /** Instant the failure was handled, for correlating the response with server logs. */
    private Instant timestamp;
}
