create table if not exists ledger(
    internal_txn_id VARCHAR PRIMARY KEY,
    merchant_id VARCHAR,
    merchant_ref VARCHAR,
    card_type VARCHAR,
    card_last4 VARCHAR,
    gross_amount NUMERIC(10, 2),
    currency VARCHAR,
    type VARCHAR,
    captured_at TIMESTAMP WITH TIME ZONE
);

create table if not exists processor_settlement(
    network_ref VARCHAR PRIMARY KEY,
    merchant_ref VARCHAR,
    merchant_id VARCHAR,
    card_last4 VARCHAR,
    card_type VARCHAR,
    settled_amount NUMERIC(10, 2),
    interchange_fee NUMERIC(10, 2),
    processor_fee NUMERIC(10, 2),
    currency VARCHAR,
    settlement_date DATE
);

create table if not exists reconciled_transactions(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_txn_id VARCHAR,
    network_ref VARCHAR,
    category VARCHAR,
    foreign key(internal_txn_id) references ledger(internal_txn_id),
    foreign key(network_ref) references processor_settlement(network_ref),
    CONSTRAINT compositeLedgerSettlement UNIQUE (internal_txn_id, network_ref)
);

--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,


--create table if not exists matches(
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    internal_txn_id VARCHAR,
--    network_ref VARCHAR,
--    category VARCHAR,
--    foreign key(internal_txn_id) references ledger(internal_txn_id),
--    foreign key(network_ref) references processor_settlement(network_ref)
--);

--    PRIMARY KEY (internal_txn_id, network_ref)
